### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically. Calling function 'Angular2SocialLoginModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function

### ISSUE THREAD

**Issue by ArielMorningstar** [heresy/angular2-social-login-example#1]
Hi, I'm doing a webapp in Angular2 and I'm using your plugin, and I followed the tutorial to make it work, and it does. But everytime my app compiles a error message appears at the terminal:

ERROR in Error encountered resolving symbol values statically. Calling function 'Angular2SocialLoginModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function.

I'm using angular-cli, so I don't have system.config.js, and the real problem comes when I run the build --aot command. It throws me the same Error and I cannot make it compile. 
However it works with the JiT compilator, but it's slow.

How can I fix that Error in my module?
Thanks!

**Comment by sv-dev2** [comment]
I do have a problem calling the method with provider in .Net core.Anyone found the solution please suggest

**Comment by logavdm** [comment]
Hi. I also Getting This errors to i am using angular cli version 1.0.0-rc.0  angular compiler-cli 2.4.8

ERROR in Error encountered resolving symbol values statically. Calling function
'Angular2SocialLoginModule', function calls are not supported. Consider replacin
g the function or lambda with a reference to an exported function, resolving sym
bol AppModule in D:/Angularjs2/Login Google/src/app/app.module.ts, resolving sym
bol AppModule in D:/Angularjs2/Login Google/src/app/app.module.ts

**Comment by techtic-chetan** [comment]
Hello,

I am getting same error, Please help me.

![image](https://cloud.githubusercontent.com/assets/20486636/23738765/ef10cf8c-04c0-11e7-984d-6ba7119f0177.png)

**Comment by kurapatijayaram** [comment]
Hi everyone, we didn't faced this error in our applications because we are not using angular-cli. Many people who are using angular-cli are facing this issue, you can check this link https://github.com/angular/angular-cli/issues/3707 . I will try to solve this issue as early as possible. If you found the solution let me know.

Thank you.

**Comment by logavdm** [comment]
In that same project i also used the  RouterModule.forRoot(appRoutes);
that's works fine but the   Angular2SocialLoginModule.initWithProviders(providers)  this lines only show me error... 


My package.json


```
{
  "name": "my-app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "angular2-modal": "^2.0.3",
    "angular2-social-login": "^2.0.2",
    "core-js": "^2.4.1",
    "ng2-bs3-modal": "^0.10.4",
    "rxjs": "^5.1.0",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-rc.0",
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.4.2",
    "typescript": "~2.0.0"
  }
}

```
My config.json


```
{
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016"
    ],
    "outDir": "../out-tsc/spec",
    "module": "commonjs",
    "target": "es6",
    "baseUrl": "",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts"
  ],
  "include": [
    "**/*.spec.ts"
  ]
}

```

**Comment by kpsrinivas** [comment]
Can you add this line and check.

`ng build --aot false`

**Comment by logavdm** [comment]
No Luck Got Same error kpsrinivas 
![image](https://cloud.githubusercontent.com/assets/4126260/23786512/80ee5ca8-0593-11e7-94ad-d906c810abaf.png)

**Comment by phongyu** [comment]
Does anyone has solution for it? I have got this issue for long, my app cannot go live because of this problem

**Comment by vijayvyas** [comment]
this code not working please upgrade the versions.

**Comment by kurapatijayaram** [comment]
@vijayvyas this code is working perfectly with JIT compiler. If you faced any issue ? please mention that. This issue with angular-cli and AOT.

**Comment by atom-morgan** [comment]
One weird quirk I'd like to add is that I'll get the same error message the first time I run `ng serve` but if I save a file to trigger webpack to recompile again, it works. Running `ng test` always shows this error.

**Comment by kpsrinivas** [comment]
Thats what is confusing me too. The AOT is straight forward. Can you try to follow this - https://www.skillmapped.com/courses/angular2-aot-webpack-lazyload and see if it works.

**Comment by kpsrinivas** [comment]
When you have "module": "corejs" its giving that bug. "module": "es2015" is working

**Comment by atom-morgan** [comment]
@kpsrinivas Are you able to run `ng build` and `ng test` successfully?

The issue seems to be all of the code before:

```
return {
  ngModule: Angular2SocialLoginModule,
  providers: [AuthService]
}
```

When all of the code before that is commented, it runs just fine using `serve`, `build`, or `test`. As soon as you add any code before the return, even just a `console.log()`, I get the error message: `Error encountered resolving symbol values statically`.

I'm actively working on finding a solution to this.

**Comment by susheelbanyal** [comment]
Hi there,
has anyone solve this problem?
I have the same problem. 
`ERROR in Error encountered resolving symbol values statically. Calling function 'Angular2SocialLoginModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol XyzModule in /var/www/html/frontendapp/src/app/xyz/xyz.module.ts, resolving symbol XyzModule in /var/www/html/frontendapp/src/app/xyz/xyz.module.ts
`
Please Help me solving this issue.
Thanks in advance.

**Comment by sulthan-ti** [comment]
I Uninstalled angular-cli, but still the problem exists

**Comment by alexzuza** [comment]
Hi! Can you try this answer?
http://stackoverflow.com/questions/43580314/calling-angular2socialloginmodule-function-calls-not-supported/43581600#43581600

**Comment by susheelbanyal** [comment]
Yes It worked for me. Thanks @alexzuza

**Comment by sulthan-ti** [comment]
@kurapatijayaram , please go through this link. yurzui give a solution for this problem

http://stackoverflow.com/questions/43580314/calling-angular2socialloginmodule-function-calls-not-supported/43581600#43581600

**Comment by kurapatijayaram** [comment]
@sulthan-ti I am aware of that solution, Sometimes it may cause you some issues with that. Give me two days time we solved this issue and also got one nice fix from one user. We will let you know when it got pushed.

Thank you.

**Comment by atom-morgan** [comment]
@susheelbanyal The issue with that solution is the `AuthService` is no longer a singleton. See [Why UserService isn't shared](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#why-_userservice_-isn-t-shared).

**Comment by alexzuza** [comment]
@atom-morgan I provided AuthService within AppModule. why is it not singleton?

**Comment by atom-morgan** [comment]
@alexzuza I provided a link above.

**Comment by alexzuza** [comment]
@atom-morgan I read this article many times. What is wrong with this solution?

**Comment by kurapatijayaram** [comment]
@atom-morgan even the solution specified by @alexzuza will maintain AuthService as a singleton.

**Comment by kurapatijayaram** [comment]
Issue fixed. Use v3.0.0 https://github.com/heresy/angular2-social-login/tree/v3.0.0
